<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="ControlParameters" Id="{ffc61bee-c1b2-401b-8834-f726b798ade9}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM ControlParameters
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="ControlParameters">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>