<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MotorEnable" Id="{26c5168c-44be-4ae1-ba38-f4c46d49dcc5}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK MotorEnable
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MotorEnable">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>